### ISSUE TITLE
Implementation of uPlot on Blazor WASM 

### ISSUE THREAD

**Issue by Ka7i** [leeoniya/uPlot#396]
I've been trying to implement uPlot on Blazor for a while now. Sadly I had no luck. I am not a professional programmer by any means. 
I'm very new to JS and I've been getting the following error when I run the application: 

    crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: then is not a function
      TypeError: then is not a function
          at new uPlot (https://localhost:44326/dist/uPlot.iife.js:3902:7)
          at generateUPlot (https://localhost:44326/js/MuPlot.js:48:10)
          at https://localhost:44326/_framework/blazor.webassembly.js:1:3942
          at new Promise (<anonymous>)
          at Object.beginInvokeJSFromDotNet (https://localhost:44326/_framework/blazor.webassembly.js:1:3908)
          at Object.w [as invokeJSFromDotNet] (https://localhost:44326/_framework/blazor.webassembly.js:1:64006)
          at _mono_wasm_invoke_js_blazor (https://localhost:44326/_framework/dotnet.5.0.1.js:1:190800)
          at do_icall (<anonymous>:wasm-function[10596]:0x194e58)
          at do_icall_wrapper (<anonymous>:wasm-function[3305]:0x79df9)
          at interp_exec_method (<anonymous>:wasm-function[2155]:0x44ad3)
    Microsoft.JSInterop.JSException: then is not a function
    TypeError: then is not a function
    at new uPlot (https://localhost:44326/dist/uPlot.iife.js:3902:7)
    at generateUPlot (https://localhost:44326/js/MuPlot.js:48:10)
    at https://localhost:44326/_framework/blazor.webassembly.js:1:3942
    at new Promise (<anonymous>)
    at Object.beginInvokeJSFromDotNet (https://localhost:44326/_framework/blazor.webassembly.js:1:3908)
    at Object.w [as invokeJSFromDotNet] (https://localhost:44326/_framework/blazor.webassembly.js:1:64006)
    at _mono_wasm_invoke_js_blazor (https://localhost:44326/_framework/dotnet.5.0.1.js:1:190800)
    at do_icall (<anonymous>:wasm-function[10596]:0x194e58)
    at do_icall_wrapper (<anonymous>:wasm-function[3305]:0x79df9)
    at interp_exec_method (<anonymous>:wasm-function[2155]:0x44ad3)
    at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__15`1[[System.Object, System.Private.CoreLib, Version=5.0.0.0, 
    Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
    at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
    at Blazor5.Pages.Visualizer.DrawMuGraph() in 
    C:\\Visualizer.razor:line 84
    at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
    at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)

I honestly haven't figured out the exact issue yet. I would greatly appreciate it if I could have some help or pointers!

**Comment by leeoniya** [comment]
> TypeError: then is not a function

i'm guessing whatever you're passing as the third argument to the uPlot constructor is neither a dom element, not a callable function, so it's ending up here:

https://github.com/leeoniya/uPlot/blob/a91bdcecae048a805f8e8be7a139f260dad065f1/src/uPlot.js#L2316

**Comment by Ka7i** [comment]
You were right. Thank you for the fast response! 
However, I'm still stuck. When I povide the third argument as document.body, the plot works fine but I can't position the graph wherever I want within the page. What I was trying to do was to pass "ctx" which is the following: 
    var ctx = document.getElementById('uChart').getContext('2d');
uChart is a reference to a canvas element on the page.
Is there any way to do that?

**Comment by leeoniya** [comment]
> When I povide the third argument as document.body, the plot works fine but I can't position the graph wherever I want within the page.

why not just create a container HTML element and position it where you want? https://jsfiddle.net/tLf92we5/

do you have a specific requirement to pre-initialize the canvas/context besides positioning the chart?

**Comment by Ka7i** [comment]
The container kind of works, but somehow I can't seem to position it properly on the page. I will first have to improve my html skills and then see what I can do about it.  
I'm still figuring out what other requirements I might need prior to initializaion. 
For now I am very grateful for your help and your great work!

**Comment by leeoniya** [comment]
gonna close this, since i think that's all that needs to be done on the uPlot side, but feel free to ask more questions here, if needed.

**Comment by nikiGagliardi** [comment]
Hi,
I continue the post.
I'm trying to use uPlot library to be able to replace Plotly.js.
Like @Ka7i , I also use the library in Blazor, specifically the server version.
so I created a simple project to test it, but, I am also getting the same error 'Uncaught TypeError: then is not a function
    at new uPlot (uPlot.iife.js:5502:5)'


_Layout.cshtml
```
...

    <script src="~/js/uPlot.iife.js"></script>
    <script src="~/js/myuplotStatic.js"></script>
    <script src="~/js/myuplot.js"></script>
</body>
</html>

```

Index.razor
```
@page "/"

<button onclick="addChart()">AddChart</button>

<div id="chart"></div>

```

myuplotStatic.js

```
function addChart() {

    // JavaScript
    var data = [[0, 1, 2, 3], [0, 1, 4, 9]]; // x and y data arrays
    var options = {
        width: 400, // chart width
        height: 300, // chart height
        scales: {
            x: { auto: true }, // auto-scale x-axis
            y: { range: [0, 10] } // manual y-axis range
        },
        series: [
            {}, // first series options (defaults to a line chart)
            { stroke: "red" } // second series options (red line)
        ]
    };
    var chart = new uPlot(options, data, document.getElementById("chart").clientWidth);
    document.getElementById("chart").innerHTML = "";
    document.getElementById("chart").appendChild(chart.root);

}
```
Am I doing something wrong?

I don't even use the razor system to call JS, but I do it directly


thanks for your time
Niki
