### ISSUE TITLE
axis._found null is not iterable

### ISSUE THREAD

**Issue by tbj128** [leeoniya/uPlot#923]
Hello! 

I've noticed when rendering a large number of datapoints across multiple series (> 1000 points, > 5 series), sometimes (~25% of the time) I will run into the following error:

```
Uncaught TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))
    at drawAxesGrid (uPlot.esm.js:4469:1)
    at uPlot.esm.js:4762:1
    at Array.forEach (<anonymous>)
    at _commit (uPlot.esm.js:4762:1)
```

This error is referencing this line: https://github.com/leeoniya/uPlot/blob/5756e3e9b91270b303157e14bd0174311047d983/src/uPlot.js#L1950 

Since the value of this field starts is only set in this method: https://github.com/leeoniya/uPlot/blob/5756e3e9b91270b303157e14bd0174311047d983/src/uPlot.js#L1787

Could there be a race condition that leads into this error? 

If not, do you have any recommendations on what might be causing this error? Thanks!

**Comment by leeoniya** [comment]
would you mind making a jsfiddle repro that i can debug? e.g. https://jsfiddle.net/vmy4hfq8/

**Comment by tbj128** [comment]
Unfortunately I'm unable to replicate in the JSFiddle so it might be due to the uplot-react wrapper we're using. I've added a null-check patch into our code base for now. I will reopen this issue if I can replicate. Thanks for the quick response.

**Comment by Klaster1** [comment]
Hi, I think I've got a 100% repro:
1. Clone https://github.com/Klaster1/timer-5
2. Switch to the "angular-18" branch.
3. Checkout the 38b1c4b9641c1ef741ba0b4407c4a90abd92098e commit.
4. Run `npm i` and `npx ng serve`.
5. Run `npx testcafe chrome --live --test="Name"`.

The test will fail with this:
```
Filters
 × Name

   1) A JavaScript error occurred on "http://localhost:4200/active/bwYe?search=game".
      Repeat test actions in the browser and check the console for errors.
      Enable the “skipJsErrors” option to ignore JavaScript errors during test execution. Learn more: "https://testcafe.io/documentation/404038/recipes/debugging/skip-javascript-errors"      
      If the website only throws this error when you test it with TestCafe, please create a new issue at:
      "https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md".

      JavaScript error details:
      TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))
          at drawAxesGrid (http://localhost:4200/@fs/C:/dev/timer-5/.angular/cache/18.0.4/vite/deps/uplot.js?v=70985e4e:3141:29)
          at http://localhost:4200/@fs/C:/dev/timer-5/.angular/cache/18.0.4/vite/deps/uplot.js?v=70985e4e:3350:33
          at Array.forEach (<anonymous>)
          at _commit (http://localhost:4200/@fs/C:/dev/timer-5/.angular/cache/18.0.4/vite/deps/uplot.js?v=70985e4e:3350:17)

      Browser: Chrome 126.0.0.0 / Windows 11

         25 |  // Reload the page, assert the filter is still open and applied
         26 |  await reload();
         27 |  await t.expect(screenTasks.taskItem.count).eql(1);
         28 |  await t.expect(screenTasks.taskName.nth(0).textContent).eql('GAME');
         29 |  // Clear the filter value with "Clear" button in the form control
       > 30 |  await t.click(screenTasks.filter.name.buttonClear);
         31 |  // Assert all tasks are displayed
         32 |  await t.expect(screenTasks.taskItem.count).eql(4);
         33 |  await t.expect(getLocationSearch()).eql('');
         34 |});
         35 |

         at <anonymous> (C:\dev\timer-5\e2e\fixtures\filters.ts:30:11)
         at fulfilled (C:\dev\timer-5\e2e\fixtures\filters.ts:5:58)



 1/1 failed (13s)

Make changes to the source files or press Ctrl+R to restart the test run.
```
Error in Chrome console:
```
uPlot.esm.js:4469 Uncaught TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))
    at drawAxesGrid (uPlot.esm.js:4469:26)
    at uPlot.esm.js:4762:28
    at Array.forEach (<anonymous>)
    at _commit (uPlot.esm.js:4762:14)
```
